### ISSUE TITLE
失去焦点，服务自动退出问题

### ISSUE THREAD

**Issue by 0xlic** [FengZhongShaoNian/share#1]
iTools 1.3.5

操作步骤
1、输入fx，打开分享窗口，打开服务开关，此时可以访问服务
2、切换到其他应用窗口，share窗口消失，服务停止，文件无法访问

必须使用窗口模式打开，且右上角置顶打开才能使用服务
![image](https://user-images.githubusercontent.com/19141867/122020747-a0017b80-cdf7-11eb-811f-7aa639ea5d7c.png)

未设置隐藏后自动退出
![image](https://user-images.githubusercontent.com/19141867/122021035-e0f99000-cdf7-11eb-8675-a492bb23c46f.png)

原版可能因为不支持多网卡，每次分享都会系统崩溃的情况，已经放弃使用，希望作者能够修复这个问题

**Comment by FengZhongShaoNian** [comment]
请问你使用的是什么操作系统？utools的版本是多少？我在ubuntu 20.04、windows 10、macOS&nbsp; mojave 10.14.6上测试都是正常的，share插件的窗口退出并不会导致分享服务停止，我用的utools的版本是v1.3.5。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FengZhongShaoNian/share"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月15日(星期二) 下午4:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FengZhongShaoNian/share] 失去焦点，服务自动退出问题 (#1)





 
iTools 1.3.5
 
操作步骤
 1、输入fx，打开分享窗口，打开服务开关，此时可以访问服务
 2、切换到其他应用窗口，share窗口消失，服务停止，文件无法访问
 
必须使用窗口模式打开，且右上角置顶打开才能使用服务
 
 
未设置隐藏后自动退出
 
 
原版可能因为不支持多网卡，每次分享都会系统崩溃的情况，已经放弃使用，希望作者能够修复这个问题

**Comment by lichen0501** [comment]
MacOS Big Sur 11.4 (20F71)
utools v1.3.5

**Comment by 0xlic** [comment]
MacOS bigSur 11.4 (20F71)
utools版本 v1.3.5

**Comment by FengZhongShaoNian** [comment]
![](https://gitee.com/fengzhongshaonian/picture-bed/raw/master/picture/20210623125140.png)
你是不是勾选了“隐藏插件后完全退出”这个选项？请不要勾选该选项，勾选该选项之后，插件隐藏的时候插件对应的进程会被关闭，插件进程被关闭了，分享服务自然也就停止了

**Comment by 0xlic** [comment]
没有勾选这个，我发现问题了，原因是勾选了 `自动分离窗口`，然后启动后自动打开了窗口，但是由于莫名的bug，导致窗口失去焦点后，进程被关闭。我试了下不勾选自动分离窗口，服务是可以后台一直运行的。
